spring.application.name=backend

# 1. AE TU TAO MYSQL DB ROI GAN LINK DB CUA MINH DE CHAY
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/se104?useSSL=false&serverTimezone=UTC

# 2. THÔNG TIN DATABASE CUA AE
spring.datasource.username=root
spring.datasource.password=Huyadmin@925#

# 3. Hibernate Auto-Generation
# UPDATE DE KHONG BI RESET DB SAU MOI LAN CHAY
spring.jpa.hibernate.ddl-auto=create

# 4. Show SQL (Helpful for debugging)
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970